### ISSUE TITLE
Portfolio spawn in sample code

### ISSUE THREAD

**Issue by majid-binary** [binary-com/websockets#10]
Spawn removed from API, but still exists in the playground.

### Steps
1. Go to https://developers.binary.com/api/ and get authenticated
2. From the drop down select Portfolio

### Result
This object is sent: `{ "portfolio": 1,  "spawn": 0}` and results in error:
```
  "echo_req": {
    "portfolio": 1,
    "spawn": 0
  },
  "version": 2,
  "error": {
    "code": "InputValidationFailed",
    "message": "Input validation failed  - $: The property spawn is not defined in the schema and the schema does not allow additional properties"
  },
  "msg_type": "error"
}
```

**Comment by borisyankov** [comment]
I fixed that, but I guess the file gets synced from the original api repo and this got overwritten,

Opened a PR
https://github.com/regentmarkets/bom-websocket-api/pull/189

**Comment by raunakkathuria** [comment]
It is fixed now and released
