### ISSUE TITLE
Get entry spot for contract

### ISSUE THREAD

**Issue by alvaxet** [binary-com/websockets#11]
Hi guys,

There has to be a way to get contract entry spot, especially for up/down contracts.
I believe portfolio call is the right place for that. 

Currently after portfolio call we have this for every contract in response (version 2):
"longcode": "USD 1.99 payout if Random 75 Index is strictly higher than entry spot at close on 2015-10-27." 

But we don't have entry spot for the contract in response.

**Comment by raunakkathuria** [comment]
We will add this in v3 as v2 is frozen, currently working on it.

**Comment by alvaxet** [comment]
Great, thank you for that.

**Comment by jy-binary** [comment]
This is done now, in the Proposal Open Contract call

**Comment by alvaxet** [comment]
When I test it here: https://developers.binary.com/api/#proposal_open_contract

I can see it in documentation on the left side,
but when I try to make a call there are no "entry_tick" and "entry_tick_time" fields in response as described in documentation.

So it seems like it doesn't work yet

**Comment by raunakkathuria** [comment]
@alvaxet Please note that this is fixed, you can also get `entry_spot` from response now 
```
{
  "echo_req": {
    "contract_id": 6066837708,
    "proposal_open_contract": 1
  },
  "proposal_open_contract": {
    "barrier": "1030.4114",
    "contract_id": "6066837708",
    "date_settlement": 1448266620,
    "validation_error": "Contract must be held for 1 minute before resale is offered.",
    "currency": "USD",
    "underlying": "RDBEAR",
    "date_start": 1448259420,
    "current_spot": "1029.1738",
    "id": "694270795dc564d0f1848aa0f9b19213",
    "is_intraday": 1,
    "is_expired": 0,
    "is_valid_to_sell": 0,
    "shortcode": "CALL_RDBEAR_2_1448259420_1448266620_S0P_0",
    "bid_price": "0.79",
    "is_forward_starting": 0,
    "longcode": "USD 2.00 payout if Random Bear is strictly higher than entry spot at 2 hours after contract start time.",
    "date_expiry": 1448266620,
    "is_path_dependent": 0,
    "ask_price": "0.83",
    "entry_spot": "1030.4114",
    "current_spot_time": "1448259452",
    "payout": "2"
  },
  "msg_type": "proposal_open_contract"
}
```

for `entry_tick` and `entry_tick_time` will be returned when you send tick contract

**Comment by alvaxet** [comment]
Thanks a lot! I can see it now.
