### ISSUE TITLE
sell contracts broken for v2 and v3

### ISSUE THREAD

**Issue by raunakkathuria** [binary-com/websockets#13]
sell contract is dependent on id from portfolio but we don't send any now from portfolio. make it dependent on contract_id

**Comment by raunakkathuria** [comment]
v3 sell is fixed and under testing. v2 is in pipeline

**Comment by raunakkathuria** [comment]
v2 is also fixed and being tested

**Comment by raunakkathuria** [comment]
This has been fixed and released. I will close it once i receive confirmation.

**Comment by JinFlark** [comment]
Sell contract is broken on v3. 
You know how to get around this error ?
