### ISSUE TITLE
Statement should accept string date filters

### ISSUE THREAD

**Issue by inexuscore** [binary-com/websockets#17]
**Profit Table** accepts **date_from** and **date_to** in both epoch and string. But **Statement** accepts only epoch values, that's a problem because we need to filter based on string values, i.e. `2015-10-30`.

**Comment by borisyankov** [comment]
I don't find it a good idea to support both. In fact I propose to drop one of the option for Profit Table.
Conversion from Epoch to string is one line in JS anyways. 
Why add complexity? If we support it one place, we will need to support it everywhere.

**Comment by raunakkathuria** [comment]
@borisyankov I will make it consistent and will drop the consistencies. As you said will keep only epoch as epoch is most widely supported

**Comment by borisyankov** [comment]
Cool. Also, there is no problem in actually adding this on the API library level.
I can add this (or anyone else for that matter) to binary-live-api so the call accepts 'epoch', 'string', 'Date', but the API protocol itself keeps just epoch.

**Comment by jy-binary** [comment]
Boris, that's a good idea. We keep epoch in the API, but binary-live-api handles other formats
