### ISSUE TITLE
Proposal open contract errors.

### ISSUE THREAD

**Issue by aminroosta** [binary-com/websockets#18]
Currently i am working on porfolio dialog and need the **ask_price** and **buy_price**(indicative) column.

I send a request to **proposal_open_contract** to get the stream of data.
but i see two error messages:

**1: Contract must be held for 1 minute before resale is offered.**  
**2: Resale of this contract is not offered.**

For the 1 , i have to try again in **1 minute** , is there a way to  **register but get the result 1 minute later ?** 

For the 2, i want to get the value of **buy_price** irrespective of whether i can sell the contract or not.
I had a chat with @raunakkathuria  and he showed me a dialog updating the value of **indicative** column, but **Resale for that contract was not offered**.

**Comment by borisyankov** [comment]
To make it a bit clearer - we don't want to get an 'error' message for something that is normal, we handle that in an error handler

Lets say if I ask, 'how many apples there are', 0 is a valid answer, and shouldn't be an 'exception there are 0 :apple:'

So when I query for info, 0 is valid answer with no error, if I try to eat an apple and the amount is 0, then we get error.

**Comment by raunakkathuria** [comment]
@aminroosta Please note that it is fixed, now it returns response in all the cases, there is no error response but you can check the flag `is_valid_to_sell` with message in `validation_error`

```
{
  "echo_req": {
    "contract_id": 6066837708,
    "proposal_open_contract": 1
  },
  "proposal_open_contract": {
    "barrier": "1030.4114",
    "contract_id": "6066837708",
    "date_settlement": 1448266620,
    "validation_error": "Contract must be held for 1 minute before resale is offered.",
    "currency": "USD",
    "underlying": "RDBEAR",
    "date_start": 1448259420,
    "current_spot": "1029.1738",
    "id": "694270795dc564d0f1848aa0f9b19213",
    "is_intraday": 1,
    "is_expired": 0,
    "is_valid_to_sell": 0,
    "shortcode": "CALL_RDBEAR_2_1448259420_1448266620_S0P_0",
    "bid_price": "0.79",
    "is_forward_starting": 0,
    "longcode": "USD 2.00 payout if Random Bear is strictly higher than entry spot at 2 hours after contract start time.",
    "date_expiry": 1448266620,
    "is_path_dependent": 0,
    "ask_price": "0.83",
    "entry_spot": "1030.4114",
    "current_spot_time": "1448259452",
    "payout": "2"
  },
  "msg_type": "proposal_open_contract"
}
```

**Comment by majid-binary** [comment]
For portfoliows page, the closest value to "Indicative" seems to be the "ask_price", but using this, we do not get the same value as displayed on the portfolio page (server parsed page). Is "ask_price" to be used, or another key?

**Comment by raunakkathuria** [comment]
@majid-binary you need to use `buy_price` for indicative price
