### ISSUE TITLE
Unsubscribe from balance changes (and use booleans for boolean values)

### ISSUE THREAD

**Issue by borisyankov** [binary-com/websockets#20]
1. Use { balance: true } to subscribe to balance updates.
2. Use { balance: false } to unsubscribe from updates.

**Comment by jy-binary** [comment]
I think you should use the Forget call to unsubscribe from updates

**Comment by borisyankov** [comment]
That is part of the proposal, move away from the general 'forget' call, as it is unnecessary.
Every call that subscribes actually has this 'true' parameter that wasn't doing anything up till now, and now very logically says 'subscribe/unsubscribe'.

**Comment by jy-binary** [comment]
I think that would require a bit of internal refactoring. We have many other things to do first.
