### ISSUE TITLE
tick data stream often stops on its own . 

### ISSUE THREAD

**Issue by Amsori** [binary-com/websockets#24]
tick data stream often stops on its own . how can tick data streams always running nonstop.if I notice usually stopped after a tick walk 200 more data. please help to fix this issue

**Comment by raitucarp** [comment]
I encounter this too.. Please fix it @borisyankov cc @raunakkathuria

**Comment by raunakkathuria** [comment]
@Amsori when tick data is stopped is the connection open at that time? Can you please check the connection state at that time and provide corresponding information here

**Comment by raunakkathuria** [comment]
@Amsori Please feel free to open this issue if it happens again. As of now it run non stop as tested
