### ISSUE TITLE
proposal_open_contract requires VERY HIGH bandwidth now

### ISSUE THREAD

**Issue by borisyankov** [binary-com/websockets#26]
Latest proposal_open_contract sends about 15kb per open position per second.
That makes it virtually impossible to to use in many mobile scenarios.

The bandwidth required now equals a video stream.
Not only may the user not have that much when being on his phone, we will also exhaust his mobile plan in 20-60mins!

**Comment by borisyankov** [comment]
The issue is that 'underlying' is not a 'string' but a crazy object ;)
Needs urgent fix.

**Comment by negar-binary** [comment]
@borisyankov the fix has been merged to master and will go live with the next release, thanks
