### ISSUE TITLE
Better validation from JSON Schema

### ISSUE THREAD

**Issue by borisyankov** [binary-com/websockets#28]
It seems we are not incorporating JSON Schema testing/validation.
Several recent bugs would have been caught by it, but weren't.
Need improving our processes.

**Comment by raunakkathuria** [comment]
@borisyankov can you please provide example where you faced this issue

**Comment by borisyankov** [comment]
One of the issues caused by that #26 (happened few more times for other calls)
The response wasn't matching the json schema, yet made it to production.
