### ISSUE TITLE
Provide trading_days category in trading_times response data

### ISSUE THREAD

**Issue by arnabk** [binary-com/websockets#30]
We have three trading_days categroy now : Weekdays (Mon-Friday), everyday (Mon-Sun) and sun_thru_thurs ( Sun to Thursday)

It would be good to have these information in the trading_times response data.

It would also be good to know the digits after decimal places for each instruments.

**Comment by borisyankov** [comment]
Digits after decimal places is gotten via ActiveSymbols call in 'pip' field.

**Comment by arnabk** [comment]
How does it help me render charts doe those which are not active now? Meaning this won't return symbols which are not currently traded

**Comment by borisyankov** [comment]
I guess we need to replace activeSymbols with 'symbols' call.
Since this should be heavily cached anyways.
activeSymbols can return just a list of the 'symbol' strings which are active, but all other details are to be retrieved once with the 'symbols' call.
