### ISSUE TITLE
Self Exclusion does not allow null/empty in WS 

### ISSUE THREAD

**Issue by nuruddeensalihu** [binary-com/websockets#36]
Hi,

I came across this issue with the self_exclusion in our websocket . When i send request with a textbox empty, it response with an error type response, highlighting the empty textboxes in the echo section. I have to fill all the text boxes before request is successful.

![image](https://cloud.githubusercontent.com/assets/12234030/11362822/0d5b8652-92d1-11e5-8fff-43ac0a685670.png)

![image](https://cloud.githubusercontent.com/assets/12234030/11362842/2fff088c-92d1-11e5-8f62-5add75573554.png)

**Comment by fayland** [comment]
could you send me the echo_req? the args you sent? @nuruddeensalihu

**Comment by nuruddeensalihu** [comment]
Hi fayland

Sorry for the late reply. Below is the snapshot from the echo_req

![image](https://cloud.githubusercontent.com/assets/12234030/11432695/baea1a9e-94ee-11e5-8603-b2ddf714f813.png)

and when i print the ``response.error.message`` . This is what i got

![image](https://cloud.githubusercontent.com/assets/12234030/11432703/ee2e5410-94ee-11e5-9db2-e033f0826343.png)

regard;
nuru;

**Comment by nuruddeensalihu** [comment]
When user enters a number that is beyond the previous set number or empty, we get the error below.

Inline image 1
![image](https://cloud.githubusercontent.com/assets/12234030/11567614/ba510d34-9a22-11e5-8b53-d52e9d843142.png)


This validations are returned by the response error message and the field is returned by the error.field. Currently , when user enters validation above the original number, the error is returned. However, when user submit empty/null, The response returned positive without error , but it does not update the entry. 

I thought when an empty/null is sent,  a similar error like the above should returned . Example from binary.com

![image](https://cloud.githubusercontent.com/assets/12234030/11567501/3dccb402-9a22-11e5-840c-356cb953ca7b.png)

![image](https://cloud.githubusercontent.com/assets/12234030/11567464/21209c10-9a22-11e5-9bbd-2d20261ec87b.png)

. Please can you ascertain what the issue is ? Or should that be implemented on the front end ?


Warm Regard;
Nuru
