### ISSUE TITLE
Account_settings.address_state does not comply to ISO standards

### ISSUE THREAD

**Issue by qingweibinary** [binary-com/websockets#37]
https://developers.binary.com/api/#set_settings

set_account_settings does not verify address_state using ISO standard code, instead
`string /^.{1,35}$/ ` is used

should change to verify if the submitted State code is valid

example (INDO)
https://en.wikipedia.org/wiki/ISO_3166-2:ID

**Comment by raunakkathuria** [comment]
@qingweibinary can you confirm if its still happening?

**Comment by qingweibinary** [comment]
@raunakkathuria I am sorry I forgotten to check, just checked it now

here's the result, address_state could be set to anything random string

<img width="607" alt="screen shot 2016-01-13 at 5 36 39 pm" src="https://cloud.githubusercontent.com/assets/14971922/12290365/548c59bc-ba1c-11e5-9b07-4a4b99363e24.png">

**Comment by raunakkathuria** [comment]
@qingweibinary ok will check and fix it then. I have open the issue again
