### ISSUE TITLE
Contract Expiry not logged via websockets unless Portfolio / Statements are refreshed on a browser

### ISSUE THREAD

**Issue by DragonFly81** [binary-com/websockets#43]
Raised as per @raunakkathuria 's request.

I'm using Version 3 (wss://ws.binaryws.com/websockets/v3?l=EN).  Sometimes, expired contracts don't drop off the Portfolio-list (i.e. when requesting the latest (open) contract list via websockets, expired contracts sometimes remain).  The sell-leg also doesn't appear in the Statements-list.

To force the deal to be logged, it is necessary to log into one's account via a browser and navigate to the "Portfolio"-url (https://www.binary.com/user/portfolio?l=EN), or, if already logged on, refresh the page.  This is problematic since it renders the websocket unreliable unless a browser-refresh is incorporated.

As mentioned in the forum, this is an old bug which I raised on the 22 September.  At the time @kavehmz commented that demo accounts didn't "Auto Sell", but he fixed the issue by letting websockets trigger "Sell Pending Contracts".

Please can this feature be reinstated.

![statement error 2](https://cloud.githubusercontent.com/assets/13745666/11929951/f8913966-a7e7-11e5-9565-2790f18e972b.jpg)

**Comment by DragonFly81** [comment]
![statement error 3](https://cloud.githubusercontent.com/assets/13745666/12025686/0177b938-adba-11e5-8cc4-63a3e00c7e52.jpg)

Please note that bug is still prevalent...

**Comment by raunakkathuria** [comment]
@DragonFly81 Please not that we have released **Transaction Stream** https://developers.binary.com/api/#transaction and **Sell expired contract** https://developers.binary.com/api/#sell_expired. Hope it provides solution to your issue

**Comment by DragonFly81** [comment]
Thanks @raunakkathuria - I haven't seen the issue occur again (recently), so also hope that it has been resolved.  Should it happen again, I'll re-open the matter.
