### ISSUE TITLE
Ticks call omit valid symbol request when one of the symbol is invalid

### ISSUE THREAD

**Issue by qingweibinary** [binary-com/websockets#49]
When calling ticks call which accept an array of symbol to be subscribed ~
like this
`{"ticks":["AS51","RDMOON","RDVENUS"],"req_id":958736814325029}`

If one of it does not provide live feed, eg AS51, the whole req failed, neither `RDMOON` not `RDVENUS` ticks are return

**Comment by qingweibinary** [comment]
@raunakkathuria

**Comment by raunakkathuria** [comment]
@qingweibinary it is fixed now. Please verify

**Comment by qingweibinary** [comment]
Tested on https://developers.binary.com/api/
It works =)

Thanks
