### ISSUE TITLE
"WrongResponse" Errors

### ISSUE THREAD

**Issue by DragonFly81** [binary-com/websockets#55]
@jy-binary @raunakkathuria @kavehmz Guys, this whole “Wrong Response”-error issue is getting out of control.  It went from an occasional annoyance to a regular phenomenon and is now at a stage where it’s actually rendering my application useless.  What’s worse is that it was originally only limited to “Proposal”-requests:

    {
      "echo_req": {
        "symbol": "R_50",
        "subscribe": "1",
        "duration": "120",
        "currency": "USD",
        "amount": "100",
        "proposal": "1",
        "basis": "stake",
        "duration_unit": "s",
        "contract_type": "CALL"
      },
      "error": {
        "message": "Sorry, an error occurred while processing your request.",
        "code": "WrongResponse"
      },
      "msg_type": "send_ask"
    }

but now crops up with “Balance”-

    {
      "echo_req": {
        "balance": "1"
      },
      "error": {
        "message": "Sorry, an error occurred while processing your request.",
        "code": "WrongResponse"
      },
      "msg_type": "balance"
    }

 “Authorise”-

    {
      "echo_req": {
        "authorize": "<Removed>"
      },
      "error": {
        "message": "Sorry, an error occurred while processing your request.",
        "code": "WrongResponse"
      },
      "msg_type": "authorize"
    }

“Ticks_History”-

    {
      "echo_req": {
        "granularity": 120,
        "count": "40",
        "ticks_history": "R_50",
        "subscribe": "1",
        "style": "candles",
        "end": "latest"
      },
      "error": {
        "message": "Sorry, an error occurred while processing your request.",
        "code": "WrongResponse"
      },
      "msg_type": "ticks_history"
    }

and even “Candles”-requests:

    {
      "echo_req": {
        "granularity": 120,
        "count": "40",
        "ticks_history": "R_50",
        "subscribe": "1",
        "style": "candles",
        "end": "latest"
      },
      "error": {
        "message": "Sorry, an error occurred while processing your request.",
        "code": "WrongResponse"
      },
      "msg_type": "ticks_history"
    }

Whatever changes were made recently, please roll them back.  Things are seriously broken.

**Comment by raunakkathuria** [comment]
This happens when there is server outage, you can check binary.com, we have put a message there also that we are undergoing maintenance. Sorry for inconvenience

**Comment by DragonFly81** [comment]
Thanks for the swift reply @raunakkathuria - "WrongResponse" is just a very ambiguous server response.  I think "NoResponse" or "TimeOut" might have been better wording to point to a server outage.  Anyways; thanks again.

**Comment by raunakkathuria** [comment]
@DragonFly81 We will take note of this for v4, we can't change v3 as its frozen and used by lots of developers. Thanks
