### ISSUE TITLE
API returns no balance sometimes

### ISSUE THREAD

**Issue by MaxPovver** [binary-com/websockets#7]
{
  "echo_req": {
    "balance": 1
  },
  "balance": [

  ],
  "version": 2,
  "debug": [
    0.015812,
    "VRTC793857"
  ],
  "msg_type": "balance"
}

Plz fix that!

**Comment by MaxPovver** [comment]
proof:  
![image](https://cloud.githubusercontent.com/assets/9439263/10489515/2271c0ec-72a6-11e5-810d-f4e522e114f6.png)

**Comment by raitucarp** [comment]
It's confirmed. I've experienced it. But rarely. 
It's sometimes.

**Comment by MaxPovver** [comment]
Had to rewrite my program to get balance from statement request, that stuff is annoying

**Comment by borisyankov** [comment]
We are investigating the issue.

**Comment by kavehmz** [comment]
@MaxPovver Is this a problem that you still encounter?

**Comment by MaxPovver** [comment]
@kavehmz can't check at the moment

**Comment by MaxPovver** [comment]
Still happens all the time

**Comment by raunakkathuria** [comment]
@MaxPovver this has been fixed. Feel free to open if it happens again
